
#ifndef ICL_CORE_TESTSUITE_IMPORT_EXPORT_H
#define ICL_CORE_TESTSUITE_IMPORT_EXPORT_H

#ifdef ICL_CORE_TESTSUITE_STATIC_DEFINE
#  define ICL_CORE_TESTSUITE_IMPORT_EXPORT
#  define ICL_CORE_TESTSUITE_NO_EXPORT
#else
#  ifndef ICL_CORE_TESTSUITE_IMPORT_EXPORT
#    ifdef icl_core_testsuite_EXPORTS
        /* We are building this library */
#      define ICL_CORE_TESTSUITE_IMPORT_EXPORT 
#    else
        /* We are using this library */
#      define ICL_CORE_TESTSUITE_IMPORT_EXPORT 
#    endif
#  endif

#  ifndef ICL_CORE_TESTSUITE_NO_EXPORT
#    define ICL_CORE_TESTSUITE_NO_EXPORT 
#  endif
#endif

#ifndef ICL_CORE_TESTSUITE_DEPRECATED
#  define ICL_CORE_TESTSUITE_DEPRECATED __declspec(deprecated)
#endif

#ifndef ICL_CORE_TESTSUITE_DEPRECATED_EXPORT
#  define ICL_CORE_TESTSUITE_DEPRECATED_EXPORT ICL_CORE_TESTSUITE_IMPORT_EXPORT ICL_CORE_TESTSUITE_DEPRECATED
#endif

#ifndef ICL_CORE_TESTSUITE_DEPRECATED_NO_EXPORT
#  define ICL_CORE_TESTSUITE_DEPRECATED_NO_EXPORT ICL_CORE_TESTSUITE_NO_EXPORT ICL_CORE_TESTSUITE_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef ICL_CORE_TESTSUITE_NO_DEPRECATED
#    define ICL_CORE_TESTSUITE_NO_DEPRECATED
#  endif
#endif

#endif /* ICL_CORE_TESTSUITE_IMPORT_EXPORT_H */
