// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: debug.proto

#include "debug.pb.h"
#include "debug.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>

static const char* debug_com_method_names[] = {
  "/debug_com/transmit_debug_info",
};

std::unique_ptr< debug_com::Stub> debug_com::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< debug_com::Stub> stub(new debug_com::Stub(channel, options));
  return stub;
}

debug_com::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_transmit_debug_info_(debug_com_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status debug_com::Stub::transmit_debug_info(::grpc::ClientContext* context, const ::debug_client& request, ::debug_server* response) {
  return ::grpc::internal::BlockingUnaryCall< ::debug_client, ::debug_server, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_transmit_debug_info_, context, request, response);
}

void debug_com::Stub::async::transmit_debug_info(::grpc::ClientContext* context, const ::debug_client* request, ::debug_server* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::debug_client, ::debug_server, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_transmit_debug_info_, context, request, response, std::move(f));
}

void debug_com::Stub::async::transmit_debug_info(::grpc::ClientContext* context, const ::debug_client* request, ::debug_server* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_transmit_debug_info_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::debug_server>* debug_com::Stub::PrepareAsynctransmit_debug_infoRaw(::grpc::ClientContext* context, const ::debug_client& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::debug_server, ::debug_client, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_transmit_debug_info_, context, request);
}

::grpc::ClientAsyncResponseReader< ::debug_server>* debug_com::Stub::Asynctransmit_debug_infoRaw(::grpc::ClientContext* context, const ::debug_client& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsynctransmit_debug_infoRaw(context, request, cq);
  result->StartCall();
  return result;
}

debug_com::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      debug_com_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< debug_com::Service, ::debug_client, ::debug_server, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](debug_com::Service* service,
             ::grpc::ServerContext* ctx,
             const ::debug_client* req,
             ::debug_server* resp) {
               return service->transmit_debug_info(ctx, req, resp);
             }, this)));
}

debug_com::Service::~Service() {
}

::grpc::Status debug_com::Service::transmit_debug_info(::grpc::ServerContext* context, const ::debug_client* request, ::debug_server* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


