// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: hand_tracking.proto

#include "hand_tracking.pb.h"
#include "hand_tracking.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace generated {

static const char* hand_tracking_com_method_names[] = {
  "/generated.hand_tracking_com/transmit_hand_data",
};

std::unique_ptr< hand_tracking_com::Stub> hand_tracking_com::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< hand_tracking_com::Stub> stub(new hand_tracking_com::Stub(channel, options));
  return stub;
}

hand_tracking_com::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_transmit_hand_data_(hand_tracking_com_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::CLIENT_STREAMING, channel)
  {}

::grpc::ClientWriter< ::generated::hand_data>* hand_tracking_com::Stub::transmit_hand_dataRaw(::grpc::ClientContext* context, ::google::protobuf::Empty* response) {
  return ::grpc::internal::ClientWriterFactory< ::generated::hand_data>::Create(channel_.get(), rpcmethod_transmit_hand_data_, context, response);
}

void hand_tracking_com::Stub::async::transmit_hand_data(::grpc::ClientContext* context, ::google::protobuf::Empty* response, ::grpc::ClientWriteReactor< ::generated::hand_data>* reactor) {
  ::grpc::internal::ClientCallbackWriterFactory< ::generated::hand_data>::Create(stub_->channel_.get(), stub_->rpcmethod_transmit_hand_data_, context, response, reactor);
}

::grpc::ClientAsyncWriter< ::generated::hand_data>* hand_tracking_com::Stub::Asynctransmit_hand_dataRaw(::grpc::ClientContext* context, ::google::protobuf::Empty* response, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::generated::hand_data>::Create(channel_.get(), cq, rpcmethod_transmit_hand_data_, context, response, true, tag);
}

::grpc::ClientAsyncWriter< ::generated::hand_data>* hand_tracking_com::Stub::PrepareAsynctransmit_hand_dataRaw(::grpc::ClientContext* context, ::google::protobuf::Empty* response, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::generated::hand_data>::Create(channel_.get(), cq, rpcmethod_transmit_hand_data_, context, response, false, nullptr);
}

hand_tracking_com::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      hand_tracking_com_method_names[0],
      ::grpc::internal::RpcMethod::CLIENT_STREAMING,
      new ::grpc::internal::ClientStreamingHandler< hand_tracking_com::Service, ::generated::hand_data, ::google::protobuf::Empty>(
          [](hand_tracking_com::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReader<::generated::hand_data>* reader,
             ::google::protobuf::Empty* resp) {
               return service->transmit_hand_data(ctx, reader, resp);
             }, this)));
}

hand_tracking_com::Service::~Service() {
}

::grpc::Status hand_tracking_com::Service::transmit_hand_data(::grpc::ServerContext* context, ::grpc::ServerReader< ::generated::hand_data>* reader, ::google::protobuf::Empty* response) {
  (void) context;
  (void) reader;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace generated

