// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: object.proto

#include "object.pb.h"
#include "object.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace generated {

static const char* object_com_method_names[] = {
  "/generated.object_com/sync_objects",
  "/generated.object_com/transmit_object",
  "/generated.object_com/delete_object",
};

std::unique_ptr< object_com::Stub> object_com::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< object_com::Stub> stub(new object_com::Stub(channel, options));
  return stub;
}

object_com::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_sync_objects_(object_com_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_transmit_object_(object_com_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_delete_object_(object_com_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::ClientReader< ::generated::Object_Instance_TF_Meta>* object_com::Stub::sync_objectsRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request) {
  return ::grpc::internal::ClientReaderFactory< ::generated::Object_Instance_TF_Meta>::Create(channel_.get(), rpcmethod_sync_objects_, context, request);
}

void object_com::Stub::async::sync_objects(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::grpc::ClientReadReactor< ::generated::Object_Instance_TF_Meta>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::generated::Object_Instance_TF_Meta>::Create(stub_->channel_.get(), stub_->rpcmethod_sync_objects_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::generated::Object_Instance_TF_Meta>* object_com::Stub::Asyncsync_objectsRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::generated::Object_Instance_TF_Meta>::Create(channel_.get(), cq, rpcmethod_sync_objects_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::generated::Object_Instance_TF_Meta>* object_com::Stub::PrepareAsyncsync_objectsRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::generated::Object_Instance_TF_Meta>::Create(channel_.get(), cq, rpcmethod_sync_objects_, context, request, false, nullptr);
}

::grpc::ClientReader< ::generated::Object_Instance_TF_Meta>* object_com::Stub::transmit_objectRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request) {
  return ::grpc::internal::ClientReaderFactory< ::generated::Object_Instance_TF_Meta>::Create(channel_.get(), rpcmethod_transmit_object_, context, request);
}

void object_com::Stub::async::transmit_object(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::grpc::ClientReadReactor< ::generated::Object_Instance_TF_Meta>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::generated::Object_Instance_TF_Meta>::Create(stub_->channel_.get(), stub_->rpcmethod_transmit_object_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::generated::Object_Instance_TF_Meta>* object_com::Stub::Asynctransmit_objectRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::generated::Object_Instance_TF_Meta>::Create(channel_.get(), cq, rpcmethod_transmit_object_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::generated::Object_Instance_TF_Meta>* object_com::Stub::PrepareAsynctransmit_objectRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::generated::Object_Instance_TF_Meta>::Create(channel_.get(), cq, rpcmethod_transmit_object_, context, request, false, nullptr);
}

::grpc::ClientReader< ::generated::Delete_Request>* object_com::Stub::delete_objectRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request) {
  return ::grpc::internal::ClientReaderFactory< ::generated::Delete_Request>::Create(channel_.get(), rpcmethod_delete_object_, context, request);
}

void object_com::Stub::async::delete_object(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::grpc::ClientReadReactor< ::generated::Delete_Request>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::generated::Delete_Request>::Create(stub_->channel_.get(), stub_->rpcmethod_delete_object_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::generated::Delete_Request>* object_com::Stub::Asyncdelete_objectRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::generated::Delete_Request>::Create(channel_.get(), cq, rpcmethod_delete_object_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::generated::Delete_Request>* object_com::Stub::PrepareAsyncdelete_objectRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::generated::Delete_Request>::Create(channel_.get(), cq, rpcmethod_delete_object_, context, request, false, nullptr);
}

object_com::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      object_com_method_names[0],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< object_com::Service, ::google::protobuf::Empty, ::generated::Object_Instance_TF_Meta>(
          [](object_com::Service* service,
             ::grpc::ServerContext* ctx,
             const ::google::protobuf::Empty* req,
             ::grpc::ServerWriter<::generated::Object_Instance_TF_Meta>* writer) {
               return service->sync_objects(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      object_com_method_names[1],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< object_com::Service, ::google::protobuf::Empty, ::generated::Object_Instance_TF_Meta>(
          [](object_com::Service* service,
             ::grpc::ServerContext* ctx,
             const ::google::protobuf::Empty* req,
             ::grpc::ServerWriter<::generated::Object_Instance_TF_Meta>* writer) {
               return service->transmit_object(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      object_com_method_names[2],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< object_com::Service, ::google::protobuf::Empty, ::generated::Delete_Request>(
          [](object_com::Service* service,
             ::grpc::ServerContext* ctx,
             const ::google::protobuf::Empty* req,
             ::grpc::ServerWriter<::generated::Delete_Request>* writer) {
               return service->delete_object(ctx, req, writer);
             }, this)));
}

object_com::Service::~Service() {
}

::grpc::Status object_com::Service::sync_objects(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::grpc::ServerWriter< ::generated::Object_Instance_TF_Meta>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status object_com::Service::transmit_object(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::grpc::ServerWriter< ::generated::Object_Instance_TF_Meta>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status object_com::Service::delete_object(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::grpc::ServerWriter< ::generated::Delete_Request>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace generated

