// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: object_prototype.proto

#include "object_prototype.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace generated {
PROTOBUF_CONSTEXPR object_prototype::object_prototype(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.mesh_name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.type_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.bounding_box_)*/nullptr
  , /*decltype(_impl_.mean_color_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct object_prototypeDefaultTypeInternal {
  PROTOBUF_CONSTEXPR object_prototypeDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~object_prototypeDefaultTypeInternal() {}
  union {
    object_prototype _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 object_prototypeDefaultTypeInternal _object_prototype_default_instance_;
}  // namespace generated
namespace generated {

// ===================================================================

class object_prototype::_Internal {
 public:
  static const ::generated::aabb& bounding_box(const object_prototype* msg);
  static const ::generated::color& mean_color(const object_prototype* msg);
};

const ::generated::aabb&
object_prototype::_Internal::bounding_box(const object_prototype* msg) {
  return *msg->_impl_.bounding_box_;
}
const ::generated::color&
object_prototype::_Internal::mean_color(const object_prototype* msg) {
  return *msg->_impl_.mean_color_;
}
void object_prototype::clear_bounding_box() {
  if (GetArenaForAllocation() == nullptr && _impl_.bounding_box_ != nullptr) {
    delete _impl_.bounding_box_;
  }
  _impl_.bounding_box_ = nullptr;
}
void object_prototype::clear_mean_color() {
  if (GetArenaForAllocation() == nullptr && _impl_.mean_color_ != nullptr) {
    delete _impl_.mean_color_;
  }
  _impl_.mean_color_ = nullptr;
}
object_prototype::object_prototype(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:generated.object_prototype)
}
object_prototype::object_prototype(const object_prototype& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  object_prototype* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.mesh_name_){}
    , decltype(_impl_.name_){}
    , decltype(_impl_.type_){}
    , decltype(_impl_.bounding_box_){nullptr}
    , decltype(_impl_.mean_color_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  _impl_.mesh_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.mesh_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_mesh_name().empty()) {
    _this->_impl_.mesh_name_.Set(from._internal_mesh_name(), 
      _this->GetArenaForAllocation());
  }
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_name().empty()) {
    _this->_impl_.name_.Set(from._internal_name(), 
      _this->GetArenaForAllocation());
  }
  _impl_.type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.type_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_type().empty()) {
    _this->_impl_.type_.Set(from._internal_type(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_bounding_box()) {
    _this->_impl_.bounding_box_ = new ::generated::aabb(*from._impl_.bounding_box_);
  }
  if (from._internal_has_mean_color()) {
    _this->_impl_.mean_color_ = new ::generated::color(*from._impl_.mean_color_);
  }
  // @@protoc_insertion_point(copy_constructor:generated.object_prototype)
}

inline void object_prototype::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.mesh_name_){}
    , decltype(_impl_.name_){}
    , decltype(_impl_.type_){}
    , decltype(_impl_.bounding_box_){nullptr}
    , decltype(_impl_.mean_color_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.mesh_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.mesh_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.type_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

object_prototype::~object_prototype() {
  // @@protoc_insertion_point(destructor:generated.object_prototype)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void object_prototype::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.mesh_name_.Destroy();
  _impl_.name_.Destroy();
  _impl_.type_.Destroy();
  if (this != internal_default_instance()) delete _impl_.bounding_box_;
  if (this != internal_default_instance()) delete _impl_.mean_color_;
}

void object_prototype::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void object_prototype::Clear() {
// @@protoc_insertion_point(message_clear_start:generated.object_prototype)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.mesh_name_.ClearToEmpty();
  _impl_.name_.ClearToEmpty();
  _impl_.type_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.bounding_box_ != nullptr) {
    delete _impl_.bounding_box_;
  }
  _impl_.bounding_box_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.mean_color_ != nullptr) {
    delete _impl_.mean_color_;
  }
  _impl_.mean_color_ = nullptr;
  _internal_metadata_.Clear<std::string>();
}

const char* object_prototype::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .generated.aabb bounding_box = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_bounding_box(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .generated.color mean_color = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_mean_color(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string mesh_name = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_mesh_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, nullptr));
        } else
          goto handle_unusual;
        continue;
      // string name = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, nullptr));
        } else
          goto handle_unusual;
        continue;
      // string type = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          auto str = _internal_mutable_type();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, nullptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* object_prototype::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:generated.object_prototype)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .generated.aabb bounding_box = 1;
  if (this->_internal_has_bounding_box()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::bounding_box(this),
        _Internal::bounding_box(this).GetCachedSize(), target, stream);
  }

  // .generated.color mean_color = 2;
  if (this->_internal_has_mean_color()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::mean_color(this),
        _Internal::mean_color(this).GetCachedSize(), target, stream);
  }

  // string mesh_name = 3;
  if (!this->_internal_mesh_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_mesh_name().data(), static_cast<int>(this->_internal_mesh_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "generated.object_prototype.mesh_name");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_mesh_name(), target);
  }

  // string name = 4;
  if (!this->_internal_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_name().data(), static_cast<int>(this->_internal_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "generated.object_prototype.name");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_name(), target);
  }

  // string type = 5;
  if (!this->_internal_type().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_type().data(), static_cast<int>(this->_internal_type().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "generated.object_prototype.type");
    target = stream->WriteStringMaybeAliased(
        5, this->_internal_type(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:generated.object_prototype)
  return target;
}

size_t object_prototype::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:generated.object_prototype)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string mesh_name = 3;
  if (!this->_internal_mesh_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_mesh_name());
  }

  // string name = 4;
  if (!this->_internal_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_name());
  }

  // string type = 5;
  if (!this->_internal_type().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_type());
  }

  // .generated.aabb bounding_box = 1;
  if (this->_internal_has_bounding_box()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.bounding_box_);
  }

  // .generated.color mean_color = 2;
  if (this->_internal_has_mean_color()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.mean_color_);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void object_prototype::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const object_prototype*>(
      &from));
}

void object_prototype::MergeFrom(const object_prototype& from) {
  object_prototype* const _this = this;
  // @@protoc_insertion_point(class_specific_merge_from_start:generated.object_prototype)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_mesh_name().empty()) {
    _this->_internal_set_mesh_name(from._internal_mesh_name());
  }
  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if (!from._internal_type().empty()) {
    _this->_internal_set_type(from._internal_type());
  }
  if (from._internal_has_bounding_box()) {
    _this->_internal_mutable_bounding_box()->::generated::aabb::MergeFrom(
        from._internal_bounding_box());
  }
  if (from._internal_has_mean_color()) {
    _this->_internal_mutable_mean_color()->::generated::color::MergeFrom(
        from._internal_mean_color());
  }
  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void object_prototype::CopyFrom(const object_prototype& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:generated.object_prototype)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool object_prototype::IsInitialized() const {
  return true;
}

void object_prototype::InternalSwap(object_prototype* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.mesh_name_, lhs_arena,
      &other->_impl_.mesh_name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.name_, lhs_arena,
      &other->_impl_.name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.type_, lhs_arena,
      &other->_impl_.type_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(object_prototype, _impl_.mean_color_)
      + sizeof(object_prototype::_impl_.mean_color_)
      - PROTOBUF_FIELD_OFFSET(object_prototype, _impl_.bounding_box_)>(
          reinterpret_cast<char*>(&_impl_.bounding_box_),
          reinterpret_cast<char*>(&other->_impl_.bounding_box_));
}

std::string object_prototype::GetTypeName() const {
  return "generated.object_prototype";
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace generated
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::generated::object_prototype*
Arena::CreateMaybeMessage< ::generated::object_prototype >(Arena* arena) {
  return Arena::CreateMessageInternal< ::generated::object_prototype >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
