// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: services.proto

#include "services.pb.h"
#include "services.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>

static const char* PingPong_method_names[] = {
  "/PingPong/Play",
};

std::unique_ptr< PingPong::Stub> PingPong::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< PingPong::Stub> stub(new PingPong::Stub(channel, options));
  return stub;
}

PingPong::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Play_(PingPong_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::ClientReaderWriter< ::Ping, ::Pong>* PingPong::Stub::PlayRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::Ping, ::Pong>::Create(channel_.get(), rpcmethod_Play_, context);
}

void PingPong::Stub::async::Play(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::Ping,::Pong>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::Ping,::Pong>::Create(stub_->channel_.get(), stub_->rpcmethod_Play_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::Ping, ::Pong>* PingPong::Stub::AsyncPlayRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::Ping, ::Pong>::Create(channel_.get(), cq, rpcmethod_Play_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::Ping, ::Pong>* PingPong::Stub::PrepareAsyncPlayRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::Ping, ::Pong>::Create(channel_.get(), cq, rpcmethod_Play_, context, false, nullptr);
}

PingPong::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PingPong_method_names[0],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< PingPong::Service, ::Ping, ::Pong>(
          [](PingPong::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::Pong,
             ::Ping>* stream) {
               return service->Play(ctx, stream);
             }, this)));
}

PingPong::Service::~Service() {
}

::grpc::Status PingPong::Service::Play(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::Pong, ::Ping>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


